### PR TITLE
Various enhancements and fixes

### LINKED ISSUE #30: Add ability to specify value of permission when adding in editor
When adding a new permission in the editor it will automatically set the permission to true. It would be nice to have an (optional?) field/checkbox to add it as false instead of having to scroll to it to switch it.

### LINKED ISSUE #31: Mark newly added permission
Currently the only way to see which permission was added is by remembering which the last one was and see which are below it. It would be nice to indicate this a bit better, e.g. via a different colored background or some icon?

### LINKED ISSUE #32: Datetime picker for Expiry input
Please add simple calendar form

### LINKED ISSUE #46: Fixed position for editing panel
Fix the specified panels for comfortable editing with too many permissions.

http://dl4.joxi.net/drive/2018/03/04/0002/2579/178707/07/dfd0f7cdfd.png

### LINKED ISSUE #51: Web editor scroll
> The web editor scroll: Currently i feel like its too small and sometimes i misclick on a group/user while trying to drag it.

Taken from lucko/LuckPerms#916

### LINKED ISSUE #57: Command box bug in the WebEditor
image

### PR DESCRIPTION
**Pull request by Turbotailz**
Resolves #30, resolves #31, resolves #32, resolves #46, resolves #51, resolves #57.

### CODE REVIEW

**Comment by lucko** [comment]
Amazing, thank you very much :)

**Comment by BrainStone** [comment]
I was referring to the first commit.

**Comment by Andre601** [comment]
I also agree with the idea of a symbol/marker to sign the new permissions, instead of making the entire row green.
But that's something you guys have to deside 😆

**Comment by Andre601** [comment]
The value-button (true/false) looks a bit "agressive".
Maybe make it a bit smaller and move it, so that the order is the same like for all set permissions?
Because it could get difficult for users (specially when they scroll through permissions like on your image) to see, what value is for what...

But so far a really nice update 👍

**Comment by BrainStone** [comment]
I think it should look the same as the button in the table.

**Pull request merged**
