### PR TITLE
Bulk editing

### LINKED ISSUE #54: Permission selection for mass action
Basically, just a check box to the left of each permission to be able to select multiple permissions for actions such as:
- Delete
- toggle values (true/false, server, world, etc) all at once
- Copy to group (sometimes multiple groups use the same permissions in different ways)

### LINKED ISSUE #86: Drag and Drop Permission nodes between groups to other "tabs"
So we finally started to migrate our servers to use one single mariadb, away from tons of lp instances with yamls backends.
As this was a big change anyway, I started to move around some group permissions. But I had to click copy on them individually, go to the other group tab and click paste.

What about a small handle that indicates you can grab a permission and drag it onto a group or user tab to automatically move it to that destination when releasing the mouse button.
Download22

### LINKED ISSUE #128: Add copy button to permissions
copy the last entry made in the web editor when adding permissions.

### LINKED ISSUE #199: Duplicate permissions.
I think that it would be cool a command/web panel option to duplicate a bunch of permissions with a different context.
For example if I have these permissions:
https://i.imgur.com/5LEMlGa.jpg
to be able to select all permissions with content server=lobby and duplicate them with context server=skyblock .

### LINKED ISSUE #262: Improve performance of verbose viewer
Verbose viewer is very laggy when the user uploads a very large log.

Consider using [`vue-virtual-scroller`](https://www.npmjs.com/package/vue-virtual-scroller)

Demo: https://akryum.github.io/vue-virtual-scroller/#/recycle

### PR DESCRIPTION
**Pull request by Turbotailz**
This PR adds bulk editing which allows users to select multiple permission nodes (across any group/user) and lets them copy, move, delete or update the nodes.

image

To do:

- [x] Copy nodes
- [x] Move nodes
- [x] Delete nodes
- [x] Update nodes
- [x] Improve performance when groups have large sets of nodes

Visit https://luckperms.turbotailz.com/editor/demo to try it out

Resolves #54 
Resolves #86
Resolves #128 
Resolves #199
Resolves #262

### CODE REVIEW

**Comment by lucko** [comment]
Had a poke around, looks great!

One small thing I noticed - seems a little laggy when selecting in groups with lots of entries. For example, open admin in the demo data and click the checkboxes to reproduce what I mean (hopefully!)

**Comment by Turbotailz** [comment]
> One small thing I noticed - seems a little laggy when selecting in groups with lots of entries. For example, open admin in the demo data and click the checkboxes to reproduce what I mean (hopefully!)

Yeah the admin group has always been a bit laggy in the demo due to how many nodes are present. I will probably look at fixing that in this PR - once I figure out how 😆

**Comment by Turbotailz** [comment]
Fixed performance for large node lists! Will also do this for the verbose viewer 👌

**Comment by Turbotailz** [comment]
Pretty much done most of the work on this now. Keen to get more people testing it out before I merge into production.

**Comment by ArranisAwesome** [comment]
This Feature is 100% needed it will make a lot of permissions easier  to work with . My 10 mins of playing round with it , it seemed prefect . would love to see this come live one time soon !

**Comment by Turbotailz** [comment]
Merging now as I have not received any other feedback than the comment above :)

**Pull request merged**
