### PR TITLE
Add selfhosting option and Not Found page and i18n support

### PR DESCRIPTION
**Pull request by Tobi406**
Add a selfhosting option that hides most of the unncessary stuff people that selfhost probably don't want.

## NOTE
The wiki submodule still has to be cloned.

## ~~(Maybe) To-Do~~
- [ ] ~~(Maybe) Add a icon to the Not Found page, tried that already but couldn't get it to work.~~
- [ ] ~~(Maybe) Add a label to the front page that says something like "Selfhosted Instance of LuckPerms Web services"~~
- [ ] ~~(Maybe) Add a link to https://luckperms.net on there.~~
- [ ] ~~Check if it works with Brain's installer script~~

## How it looks like
image

image

### CODE REVIEW

**Comment by Turbotailz** [comment]
This is a cool idea. I think it would be a better idea to import the config inside the Vuex store instead of requiring it in each component.

**Comment by Turbotailz** [comment]
This also gives me an idea on allowing people to theme the app by providing their own logos and colours...

**Comment by Tobi406** [comment]
I meant strings...
Anyways, just had some time and did that. I that mechanism is acceptable I'll also do the other strings as currently it's just the navigation bar.
**Language selection menu:**
image

**Comment by Turbotailz** [comment]
Hmm, there is actually a package for Vue i18n which may be better to use.

**Comment by Tobi406** [comment]
That is..... a good idea actually. I'll check that out ~~atleaat my selector can stay~~

**Comment by Tobi406** [comment]
Should I continue to use the `lang` query parameter for knowing what a user has gotten as locale. Or maybe some sort of middle way (optional `lang` parameter, so users could include it in their editor link for example if they want)?

**Comment by Tobi406** [comment]
The editor loads slow if called with the lang parameter, probably because I use watch, didn't found another solution tough.

**Comment by Venlious** [comment]
Instead of cramming the `main.js` with the all translatable messages, I suggest having one main `messages.js` and importing that instead. In this `messages.js` you could then import all available languages, such as `messages_en.js`, `messages_de.js`. Each language would then have its own file, making it more maintainable in my opinion.

**Comment by Turbotailz** [comment]
Totally agree ^

**Comment by Tobi406** [comment]
Was more a temporary solution to see if my approach is ok. But should have done that already anyways.

**Comment by BrainStone** [comment]
Wouldn't make a lot more sense to separate the selfhosting options and the translations stuff into two PRs?

**Comment by Turbotailz** [comment]
> Wouldn't make a lot more sense to separate the selfhosting options and the translations stuff into two PRs?

I also agree with this, i18n will be a pretty big project in itself and it'd make more sense to separate it into its own branch/PR.

**Comment by Tobi406** [comment]
Split up some things in #228 and #229. Will wait until those two are merged and then create PRs for the rest.

**Comment by Tobi406** [comment]
Will close as most features are in seperate PRs now. And I'll just no longer add i18n as I think the benefits of it aren't that big.

**Comment by Turbotailz** [comment]
I think it's still worth doing i18n but we can shelve it for another time. Thanks for trying!

**Pull request closed without merging**
