### PR TITLE
Bigger size for avatar

### PR DESCRIPTION
**Pull request by DolphinGamerYT**
Changed the size from 8 (https://prnt.sc/12opvbe) to 32 (https://prnt.sc/12opwsp).

### CODE REVIEW

**Comment by lucko** [comment]
What browser are you using?

**Comment by DolphinGamerYT** [comment]
> What browser are you using?

Currently I'm using Brave. I will try with more browsers.

**Comment by lucko** [comment]
I know it works fine on Chrome, Edge, Firefox, Opera, Safari...

https://developer.mozilla.org/en-US/docs/Web/CSS/image-rendering#browser_compatibility

**Comment by DolphinGamerYT** [comment]
Brave runs under chromium, so it should look good.

**Comment by DolphinGamerYT** [comment]
I've just tested it on Firefox and Chrome, and it actually looks good on Firefox, but not on chrome. (https://prnt.sc/12rh4sy)

Maybe a chromium issue?

**Comment by Turbotailz** [comment]
This is actually resolved by disabling the `image-rendering: optimize-quality` property in Chrome.

image

**Comment by DolphinGamerYT** [comment]
> This is actually resolved by disabling the `image-rendering: optimize-quality` property in Chrome.
> 
> image

It also worked for me

**Comment by lucko** [comment]
This should be set already? Unless I'm missing something

**Comment by DolphinGamerYT** [comment]
> This should be set already? Unless I'm missing something

I needed to disable it on chrome for it to look good, like @Turbotailz said.

**Comment by lucko** [comment]
Ah, I see! Thanks

**Pull request closed without merging**
