### PR TITLE
Add wiki for website

### PR DESCRIPTION
**Pull request by Tobi406**
Adds [lp-vue-wiki](https://github.com/Turbotailz/lp-vue-wiki) to this website repo.
Made some small changes to CSS to get it working.

## Examples
**Home page:**
grafik

**Why LuckPerms page:**
grafik

## Current issues
- Not all emojis are rendered. We could use Unicode emojis in the wiki repo in all cases instead of eg. `:rocket:` for example.
- Links are not local, but this has to be fixed in the wiki repo too.
- Tabs are sometimes too long, will look into it

### CODE REVIEW

**Comment by Andre601** [comment]
I personally would've suggested MkDocs as it allows lots of customisation from the start (using separate CSS and JS files) and also integrates things like emojis through extensions (in this case the Emojis extension of PyMdown)

But I guess vue is also okay. 🤷‍♂

**Comment by Turbotailz** [comment]
Amazing <3

**Comment by Andre601** [comment]
Is there a live-version of this wiki viewable?

**Comment by Tobi406** [comment]
Yes, https://luckperms.turbotailz.com/wiki

**Comment by Andre601** [comment]
Alright and I see what you mean with the emojis.
Did you try to use the unicode/raw versions of them?
Or perhaps vue offers an option to integrate emojis from places like Twemoji?

**Comment by Tobi406** [comment]
Yes, unicode works fine.
There's also a plugin for `markdown-it` (which we currently use): `markdown-it-emoji` that can render emojis. Trying to get it working, still new with Vue.

**Comment by Andre601** [comment]
I never used vue, so I can't help there.
I only used MkDocs so far, but can see myself pretty decent with it by now.

**Comment by Tobi406** [comment]
Added #192 to add the `markdown-it-emoji` plugin

**Pull request merged**
