### PR TITLE
Add wiki back

### PR DESCRIPTION
**Pull request by Tobi406**
Add the wiki back. Links on the sidebar don't "load" the page, so don't merge this in yet.

### CODE REVIEW

**Comment by Tobi406** [comment]
Tracked down the issue, the router on [this line](https://github.com/lucko/LuckPermsWeb/pull/268/files#diff-bad967123662fbec39c447e6096b062bR59) doesn't has a push method.

**Comment by Turbotailz** [comment]
I tried finding what you would use instead but it seems that it should be `this.$router.push()` so... ¯\_(ツ)_/¯

**Comment by Tobi406** [comment]
We also get this nice console error and the article doesn't load at all: 
image
Maybe we should just use `window.open` in all cases?

**Comment by Turbotailz** [comment]
Nuxt is using Vue Router so there must be an internal method we can use. Using the browser methods will force a page reload which is not what we want (I realise now that I was doing this previously and is not the best method).

**Comment by Tobi406** [comment]
Ok, I think I got it tracked down, [this](https://github.com/lucko/LuckPermsWeb/pull/268/files#diff-bad967123662fbec39c447e6096b062bR98) is only called client-side, but not server-side.

**Comment by Tobi406** [comment]
We might be able to use a middleware, but I don't think we can run the method from one

**Comment by Tobi406** [comment]
I think I got it. It are the `foo?.bar` things in `store/index.js`, no idea what these actually do tough

**Comment by Turbotailz** [comment]
Oh, that's called "optional chaining", it's only supported in Node version 14 so you will need to update your Node by the sounds of it.

**Comment by Tobi406** [comment]
Applying [@babel/plugin-proposal-optional-chaining](https://www.npmjs.com/package/@babel/plugin-proposal-optional-chaining) seems to fix the the issue.

**Comment by Tobi406** [comment]
Ok, so I think I got a (half) working thing (finally! :tada:).

I query the raw contents of the files from GitHub periodically in a server middleware. 
Then I fetch these saved contents using a fetch action from nuxt and then display them by doing a render inline.

**Comment by Tobi406** [comment]
Superseded by #283

**Pull request closed without merging**
