### PR TITLE
Added OctoCat :octocat:

### PR DESCRIPTION
**Pull request by BrainStone**
Need I say more?

### CODE REVIEW

**Comment by lucko** [comment]
My thoughts:

* Can we make the whole thing slightly smaller? I kinda like the idea of linking people back to the repo, but in reality, most people won't care - therefore don't want it to be too visible

* Match the colors with the sidebar - currently the white/cream color is used by the table only, which is the most important part of the page. I feel stuff like the header, footer and in this case octocat should be the navy coloring.

**Comment by BrainStone** [comment]
I can make it smaller, no problem.

Erm I think it blends in really well in the bottom corner there. But which color codes are you proposing for the cat and the triangle?

**Comment by BrainStone** [comment]
*Correction: I changed the colors locally. But not in the commit.

**Comment by BrainStone** [comment]
Fixed everything. 60px should be small enough (was 80px) before.

**Comment by lucko** [comment]
Maybe make the cat turn green (the color of the text in the footer) when hovered?

but yeah, that's definitely much better already 😄

**Comment by BrainStone** [comment]
Will do that. That would be a nice touch

**Comment by BrainStone** [comment]
There you go :)

**Pull request merged**
